
import { CareHome, CareType, Language } from "./types";

export const MOCK_HOMES: CareHome[] = [
  // Berlin (10xxx)
  { id: '1', name: 'Seniorenzentrum Waldruhe', zip: '10115', city: 'Berlin', distance: 2.5, supportedTypes: [CareType.LONG_TERM, CareType.SHORT_TERM], description: 'Quiet location near the park.' },
  { id: '2', name: 'Pflegeheim Sonnenschein', zip: '10119', city: 'Berlin', distance: 4.0, supportedTypes: [CareType.LONG_TERM, CareType.DAY_CARE], description: 'Specialized in dementia care.' },
  { id: '3', name: 'Haus Am See', zip: '10245', city: 'Berlin', distance: 8.2, supportedTypes: [CareType.SHORT_TERM], description: 'Modern facilities with lake view.' },
  { id: '4', name: 'St. Michael Pflege', zip: '10405', city: 'Berlin', distance: 12.0, supportedTypes: [CareType.LONG_TERM, CareType.SHORT_TERM, CareType.DAY_CARE], description: 'Full service care center.' },

  // Munich (80xxx)
  { id: '5', name: 'Residenz Isarwinkel', zip: '80469', city: 'München', distance: 3.0, supportedTypes: [CareType.LONG_TERM, CareType.SHORT_TERM], description: 'Exclusive residence near the Isar river.' },
  { id: '6', name: 'Pflegeheim Nymphenburg', zip: '80638', city: 'München', distance: 5.5, supportedTypes: [CareType.LONG_TERM, CareType.DAY_CARE], description: 'Close to the palace gardens.' },
  { id: '7', name: 'Seniorenstift Schwabing', zip: '80802', city: 'München', distance: 4.2, supportedTypes: [CareType.SHORT_TERM, CareType.DAY_CARE], description: 'In the heart of the artistic district.' },

  // Cologne (50xxx)
  { id: '8', name: 'Rheinufer Residenz', zip: '50668', city: 'Köln', distance: 1.5, supportedTypes: [CareType.LONG_TERM, CareType.SHORT_TERM], description: 'Direct view of the Rhine and Cathedral.' },
  { id: '9', name: 'Seniorenhaus Ehrenfeld', zip: '50823', city: 'Köln', distance: 6.0, supportedTypes: [CareType.LONG_TERM, CareType.DAY_CARE], description: 'Vibrant community atmosphere.' },

  // Frankfurt (60xxx)
  { id: '10', name: 'Main-Taunus Pflege', zip: '60311', city: 'Frankfurt am Main', distance: 2.0, supportedTypes: [CareType.LONG_TERM, CareType.SHORT_TERM, CareType.DAY_CARE], description: 'Central location with modern medical facilities.' },
  { id: '11', name: 'Residenz Westend', zip: '60325', city: 'Frankfurt am Main', distance: 3.5, supportedTypes: [CareType.LONG_TERM], description: 'Upscale living for seniors.' },

  // Stuttgart (70xxx)
  { id: '12', name: 'Schlossgarten Residenz', zip: '70173', city: 'Stuttgart', distance: 1.8, supportedTypes: [CareType.LONG_TERM, CareType.SHORT_TERM], description: 'Next to the state theater and parks.' },
  { id: '13', name: 'Haus am Killesberg', zip: '70191', city: 'Stuttgart', distance: 4.5, supportedTypes: [CareType.LONG_TERM, CareType.DAY_CARE], description: 'Green surroundings and panoramic views.' },
];

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.DE]: {
    'app.title': 'PflegeNavi24',
    'landing.title': 'Pflege einfach finden.',
    'landing.family': 'Ich suche einen Pflegeplatz',
    'landing.sub.family': 'Finden Sie Heimplätze, Kurzzeitpflege oder Tagespflege.',
    'landing.carehome': 'Ich bin eine Pflegeeinrichtung',
    'landing.sub.carehome': 'Verwalten Sie freie Plätze und sehen Sie passende Anfragen.',
    'btn.next': 'Weiter',
    'btn.back': 'Zurück',
    'btn.search': 'Suchen',
    'btn.submit': 'Anfrage absenden',
    'btn.home': 'Zurück zum Start',
    'step.careType': 'Pflegeart wählen',
    'step.medical': 'Gesundheit',
    'step.region': 'Region & Radius',
    'step.homes': 'Heimwahl',
    'step.admission': 'Daten',
    'step.contact': 'Kontakt',
    'step.documents': 'Dokumente & Extras',
    'step.consents': 'Rechtliches',
    'type.longterm': 'Heimplatz (Dauerpflege)',
    'type.shortterm': 'Kurzzeitpflege',
    'type.daycare': 'Tagespflege',
    'label.carelevel': 'Pflegegrad',
    'label.dementia': 'Demenzstatus',
    'label.conditions': 'Medizinische Angaben & Zustände',
    'cond.mobility': 'Mobilitätseinschränkung',
    'cond.psychiatric': 'Psychiatrische Erkrankungen',
    'cond.palliative': 'Palliativpflege',
    'cond.diabetes': 'Diabetes (Insulinpflichtig)',
    'cond.stroke': 'Schlaganfall',
    'cond.diet': 'Spezielle Diät / Ernährung',
    'cond.woundcare': 'Wundversorgung',
    'cond.incontinence': 'Inkontinenz',
    'opt.dementia_yes': 'Demenz diagnostiziert',
    'opt.dementia_no': 'Keine Demenz',
    'opt.dementia_unsure': 'Unsicher / In Abklärung',
    'label.location': 'Postleitzahl oder Stadt',
    'label.zip': 'Postleitzahl',
    'label.radius': 'Umkreis (km)',
    'label.address_street': 'Straße',
    'label.address_housenr': 'Hausnr.',
    'label.address_zip': 'PLZ',
    'label.address_city': 'Ort',
    'label.address_notes': 'Adress-Zusatz / Hinweise',
    'label.parking': 'Benötigen Sie einen Besucherparkplatz?',
    'label.upload_doctor': 'Arztbrief hochladen',
    'label.upload_poa': 'Generalvollmacht hochladen',
    'consent.45b': 'Ich bestätige, dass ich den Entlastungsbetrag nach §45b SGB XI nutzen möchte und die Direktabrechnung in Höhe von 74,99 € pro Einsatz mit meiner Pflegekasse gestatte.',
    'consent.agb': 'Ich akzeptiere die AGB.',
    'consent.privacy': 'Ich stimme der Datenverarbeitung zu.',
    'consent.waitlist': 'Bitte setzen Sie mich auf die Warteliste.',
    'chat.trigger': 'Hilfe & Assistent',
    'chat.placeholder': 'Fragen Sie uns etwas...',
    'carehome.login': 'Pflegeheim Login',
    'carehome.dashboard': 'Verfügbarkeit verwalten',
    'carehome.free': 'Platz Frei',
    'carehome.occupied': 'Belegt',
    'success.title': 'Anfrage gesendet!',
    'success.message': 'Wir haben eine E-Mail an {email} gesendet. Wir melden uns per SMS, sobald ein Platz frei wird.',
  },
  [Language.EN]: {
    'app.title': 'PflegeNavi24',
    'landing.title': 'Care made simple.',
    'landing.family': 'I am looking for a care place',
    'landing.sub.family': 'Find long-term, short-term, or day care services.',
    'landing.carehome': 'I am a care home',
    'landing.sub.carehome': 'Manage your beds and view matching requests.',
    'btn.next': 'Next',
    'btn.back': 'Back',
    'btn.search': 'Search',
    'btn.submit': 'Submit Request',
    'btn.home': 'Return to Start',
    'step.careType': 'Care Type',
    'step.medical': 'Health',
    'step.region': 'Region',
    'step.homes': 'Select Homes',
    'step.admission': 'Data',
    'step.contact': 'Contact',
    'step.documents': 'Documents & Extras',
    'step.consents': 'Legal',
    'type.longterm': 'Long-term Care',
    'type.shortterm': 'Short-term Care',
    'type.daycare': 'Day Care',
    'label.carelevel': 'Care Level',
    'label.dementia': 'Dementia Status',
    'label.conditions': 'Medical Conditions',
    'cond.mobility': 'Mobility Restriction',
    'cond.psychiatric': 'Psychiatric Conditions',
    'cond.palliative': 'Palliative Care',
    'cond.diabetes': 'Diabetes',
    'cond.stroke': 'Stroke',
    'cond.diet': 'Special Diet',
    'cond.woundcare': 'Wound Care',
    'cond.incontinence': 'Incontinence',
    'opt.dementia_yes': 'Dementia Diagnosed',
    'opt.dementia_no': 'No Dementia',
    'opt.dementia_unsure': 'Unsure',
    'label.location': 'Postal Code or City',
    'label.zip': 'Postal Code',
    'label.radius': 'Radius (km)',
    'label.address_street': 'Street',
    'label.address_housenr': 'No.',
    'label.address_zip': 'Zip',
    'label.address_city': 'City',
    'label.address_notes': 'Address Notes',
    'label.parking': 'Do you need a visitor parking spot?',
    'label.upload_doctor': 'Upload Doctor\'s Letter',
    'label.upload_poa': 'Upload General Power of Attorney',
    'consent.45b': 'I confirm that I want to use the relief amount under §45b SGB XI and allow direct billing of €74.99 per use with my care insurance.',
    'consent.agb': 'I accept the General Terms.',
    'consent.privacy': 'I agree to data processing.',
    'consent.waitlist': 'Please put me on the waiting list.',
    'chat.trigger': 'Help & Assistant',
    'chat.placeholder': 'Ask us anything...',
    'carehome.login': 'Care Home Login',
    'carehome.dashboard': 'Manage Availability',
    'carehome.free': 'Place Free',
    'carehome.occupied': 'Occupied',
    'success.title': 'Request Sent!',
    'success.message': 'We have sent an email to {email}. We will notify you via SMS when a place becomes free.',
  },
  [Language.TR]: {
    'app.title': 'PflegeNavi24',
    'landing.title': 'Bakım kolayca bulunur.',
    'landing.family': 'Bakım yeri arıyorum',
    'landing.sub.family': 'Uzun süreli, kısa süreli veya gündüz bakım hizmetleri bulun.',
    'landing.carehome': 'Bakım evi yetkilisiyim',
    'landing.sub.carehome': 'Yatak durumunu yönetin ve eşleşen talepleri görüntüleyin.',
    'btn.next': 'İleri',
    'btn.back': 'Geri',
    'btn.search': 'Ara',
    'btn.submit': 'Talebi Gönder',
    'btn.home': 'Başa Dön',
    'step.careType': 'Bakım Türü',
    'step.medical': 'Sağlık',
    'step.region': 'Bölge',
    'step.homes': 'Ev Seçimi',
    'step.admission': 'Veriler',
    'step.contact': 'İletişim',
    'step.documents': 'Belgeler ve Ekstralar',
    'step.consents': 'Yasal',
    'type.longterm': 'Uzun Süreli Bakım',
    'type.shortterm': 'Kısa Süreli Bakım',
    'type.daycare': 'Gündüz Bakımı',
    'label.carelevel': 'Bakım Seviyesi (Pflegegrad)',
    'label.dementia': 'Demans Durumu',
    'label.conditions': 'Tıbbi Durumlar',
    'cond.mobility': 'Ciddi Hareket Kısıtlılığı',
    'cond.psychiatric': 'Psikiyatrik Rahatsızlıklar',
    'cond.palliative': 'Palyatif Bakım',
    'cond.diabetes': 'Diyabet',
    'cond.stroke': 'İnme / Felç',
    'cond.diet': 'Özel Diyet',
    'cond.woundcare': 'Yara Bakımı',
    'cond.incontinence': 'İnkontinans',
    'opt.dementia_yes': 'Demans Teşhisi Var',
    'opt.dementia_no': 'Demans Yok',
    'opt.dementia_unsure': 'Emin Değil / Belirsiz',
    'label.location': 'Posta Kodu veya Şehir',
    'label.zip': 'Posta Kodu',
    'label.radius': 'Yarıçap (km)',
    'label.address_street': 'Cadde/Sokak',
    'label.address_housenr': 'No.',
    'label.address_zip': 'Posta Kodu',
    'label.address_city': 'Şehir',
    'label.address_notes': 'Adres Notları',
    'label.parking': 'Ziyaretçi park yeri gerekiyor mu?',
    'label.upload_doctor': 'Doktor Mektubu Yükle',
    'label.upload_poa': 'Genel Vekaletname Yükle',
    'consent.45b': '§45b SGB XI kapsamındaki yardım tutarını kullanmak istediğimi ve kullanım başına 74,99 € tutarındaki doğrudan faturalandırmayı bakım sigortamla onayladığımı teyit ederim.',
    'consent.agb': 'Genel Şartları kabul ediyorum.',
    'consent.privacy': 'Veri işlemeyi kabul ediyorum.',
    'consent.waitlist': 'Lütfen beni bekleme listesine alın.',
    'chat.trigger': 'Yardım ve Asistan',
    'chat.placeholder': 'Bize bir şey sorun...',
    'carehome.login': 'Bakım Evi Girişi',
    'carehome.dashboard': 'Müsaitlik Yönetimi',
    'carehome.free': 'Yer Var',
    'carehome.occupied': 'Dolu',
    'success.title': 'Talep Gönderildi!',
    'success.message': '{email} adresine bir e-posta gönderdik. Yer açıldığında size SMS ile haber vereceğiz.',
  }
};
